language: python
python:
    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - 3.6
install:
    - "dd if=/dev/zero of=blank_rom.gb bs=1k count=32"
    - "pip install ."
script: "python3 -m unittest discover tests"
